apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchandise-app
  namespace: merchandise
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merchandise-app
  template:
    metadata:
      labels:
        app: merchandise-app
    spec:
      containers:
      - name: merchandise
        image: acrsttestuks001.azurecr.io/merchandiseapp:0.0.2
        ports:
        - containerPort: 3000